### ISSUE TITLE
issue with the data in the csv() XHR function

### ISSUE THREAD

**Issue by pawel2105** [jckr/example-react-app#1]
Hey Jerome

Great series. I'm following along and I'm hitting a bit of a roadblock with the `csv()` function. My `componentWillMount` looks exactly like yours:

```
    csv('./data/birthdeathrates.csv', (error, data) => {
      if (error) {
        this.setState({ loadError: true })
      }

      this.setState({
        data: data.map(d => ({ ...d, x: Number(d.birth), y: Number(d.death)}))
      })
    })
```

But instead of returning the data, it seems to be returning the very page that this JS runs on. If I move this `csv()` function to the `render()` block and console log each of the data iterations, I get the following console output:

<img width="913" alt="screen shot 2016-11-15 at 3 08 38 pm" src="https://cloud.githubusercontent.com/assets/811477/20306862/47ecaac0-ab45-11e6-8140-ef210dc8debd.png">

My directory structure is like yours too:

    ./src/App.js
    ./data/birthdeathrates.csv

My `package.json` file has locked the following lib versions but I can't find any obvious changes in those that would cause this:

```
{
  "devDependencies": {
    "react-scripts": "0.7.0",
    "react-addons-shallow-compare": ">=0.14.0"
  },
  "dependencies": {
    "d3-request": "^1.0.2",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-vis": "^0.6.5"
  }
  ...
}
```

I'm just thinking out loud while I try debug this, in case anyone else following this tutorial runs into the same problem. If/when I figure this out, I'll provide the solution to this issue.

**Comment by pawel2105** [comment]
I took the easy way out. I removed the csv import statement, added the data as a variable above the App class component definition:

```
const csvData = [
  ["alg",36.4,14.6],
  ["con",37.3,8],
  ["egy",42.1,15.3],
  ["gha",55.8,25.6],
  ["ict",56.1,33.1],
  ["mag",41.8,15.8],
  ["mor",46.1,18.7],
  ["tun",41.7,10.1],
  ["cam",41.4,19.7],
  ["cey",35.8,8.5],
  ["chi",34,11],
  ["tai",36.3,6.1],
  ["hkg",32.1,5.5],
  ["ind",20.9,8.8],
  ["ids",27.7,10.2],
  ["irq",20.5,3.9],
  ["isr",25,6.2],
  ["jap",17.3,7],
  ["jor",46.3,6.4],
  ["kor",14.8,5.7],
  ["mal",33.5,6.4],
  ["mog",39.2,11.2],
  ["phl",28.4,7.1],
  ["syr",26.2,4.3],
  ["tha",34.8,7.9],
  ["vit",23.4,5.1],
  ["can",24.8,7.8],
  ["cra",49.9,8.5],
  ["dmr",33,8.4],
  ["gut",47.7,17.3],
  ["hon",46.6,9.7],
  ["mex",45.1,10.5],
  ["nic",42.9,7.1],
  ["pan",40.1,8],
  ["usa",21.7,9.6],
  ["arg",21.8,8.1],
  ["bol",17.4,5.8],
  ["bra",45,13.5],
  ["chl",33.6,11.8],
  ["clo",44,11.7],
  ["ecu",44.2,13.5],
  ["per",27.7,8.2],
  ["urg",22.5,7.8],
  ["ven",42.8,6.7],
  ["aus",18.8,12.8],
  ["bel",17.1,12.7],
  ["brt",18.2,12.2],
  ["bul",16.4,8.2],
  ["cze",16.9,9.5],
  ["dem",17.6,19.8],
  ["fin",18.1,9.2],
  ["fra",18.2,11.7],
  ["gmy",18,12.5],
  ["gre",17.4,7.8],
  ["hun",13.1,9.9],
  ["irl",22.3,11.9],
  ["ity",19,10.2],
  ["net",20.9,8],
  ["now",17.5,10],
  ["pol",19,7.5],
  ["pog",23.5,10.8],
  ["rom",15.7,8.3],
  ["spa",21.5,9.1],
  ["swe",14.8,10.1],
  ["swz",18.9,9.6],
  ["rus",21.2,7.2],
  ["yug",21.4,8.9],
  ["ast",21.6,8.7],
  ["nzl",25.5,8.8],
]
```

I changed my `componentWillMount` function to:

```
componentWillMount() {
    this.setState({
      data: csvData.map(d => ({ ...d, x: Number(d[1]), y: Number(d[2])}))
    })
  }
```

This change requires some slight adjusting for the `HintContent` file. Remove the destructuring definition line and replace `{country}` etc. with `{value[0]}` etc.

**Comment by wadehenning** [comment]
Thank you!
